# Generated by Django 4.2.6 on 2024-01-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccountmodel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='useraccountmodel',
            name='phone_no',
        ),
        migrations.AddField(
            model_name='useraccountmodel',
            name='user_category',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('author', 'Author'), ('reader', 'Reader')], max_length=10, null=True),
        ),
    ]
