# Generated by Django 4.2.6 on 2024-01-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_useraccountmodel_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccountmodel',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_picture/'),
        ),
    ]
